name: 'vib'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - master
    types:
      - assigned 
      - opened 
      - synchronize 
      - reopened
    paths:
      - 'bitnami/wordpress/*'
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
  VIB_REPLACE_PUBLIC_URL: ${{ secrets.VIB_REPLACE_PUBLIC_URL }} # Replaces with VPN-friendly url
jobs:
  cp-validate: # make sure chart is linted/safe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vmware-samples/vmware-image-builder-examples/vib-action@main

  cp-k8s-verify: # verify in multiple target platforms
    runs-on: ubuntu-latest
    needs: [cp-validate]
    strategy:
      matrix:
       include:
         - target-platform: gke
           target-platform-id: 91d398a2-25c4-4cda-8732-75a3cfc179a1
         - target-platform: aks
           target-platform-id: 7b13a7bb-011c-474f-ad71-8152fc321b9e
         - target-platform: tkg-1.3.0-aws
           target-platform-id: 7ddab896-2e4e-4d58-a501-f79897eba3a0
      fail-fast: false
    name: K8s verify ${{ matrix.target-platform}}
    steps:
      - uses: actions/checkout@v2
      - uses: vmware-samples/vmware-image-builder-examples/vib-action@main
        with: 
          pipeline: cp-platform-verify.json
        env: 
          TARGET_PLATFORM: ${{ matrix.target-platform-id }}
